version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(funcName)s - %(bis_process_name)s:%(process)s - %(message)s'

filters:
    bisNameFilter:
        (): digiboard._helper.BisProcessNameFilter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
    filters: [bisNameFilter]
  file:
    class : logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    when: midnight
    formatter: simple
    filename: 'log/digiboard_log.log'
    filters: [bisNameFilter]
root:
  level: DEBUG
  handlers: [file]
disable_existing_loggers: False